apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-internal-kubectl-role
  namespace: {{ .Values.namespace  | default "default" }}
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: 
  - "valkeys.valkey.andino.io"
  resources:
  - valkeys
  verbs: ["get", "list", "watch"]
