apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-internal-kubectl-role-binding
  namespace: {{ .Values.namespace  | default "default" }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-internal-kubectl
roleRef:
  kind: Role
  name: {{ .Release.Name }}-internal-kubectl-role
  apiGroup: rbac.authorization.k8s.io
