apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-restic-password
  namespace: {{ .Values.namespace  | default "default" }}
type: Opaque
data:
  {{- if .Values.restic_password }}
  password: {{ .Values.restic_password | b64enc }}
  {{- else }}
  password: {{ randAlphaNum 20 | b64enc }}
  {{- end }}

