#
# The encryption has to be done like this: echo -n supersecret | base64 
# This is to avoid the \n at the end of the encryption
#
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3-credentials
  namespace: {{ .Values.namespace  | default "default" }}
type: Opaque
data:
  access_key: {{ .Values.s3.access_key | b64enc }}
  secret_access_key: {{ .Values.s3.secret_key | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-restic-password
  namespace: {{ .Values.namespace  | default "default" }}
type: Opaque
data:
  {{- if .Values.restic_password }}
  password: {{ .Values.restic_password | b64enc }}
  {{- else }}
  password: {{ randAlphaNum 20 | b64enc }}
  {{- end }}

